spring:
  application:
    name: ai-reader
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus-2025-09-11
        api-key: ${your-key}